### ISSUE TITLE
How about plugin

### ISSUE THREAD

**Issue by fesily** [LuaLS/LLS-Addons#110]
I've noticed that there doesn't seem to be an example that provides how to handle plugin files in the codebase

**Comment by carsakiller** [comment]
This was intentional, as I hadn't found a way yet to make the install easy and safe. Plugins will be installed if they are [in an addon](https://luals.github.io/wiki/addons/#addon-anatomy), but must be [manually enabled](https://luals.github.io/wiki/settings/#runtimeplugin) using their path. I didn't want to automatically enable the execution of potentially unknown code, but I also wasn't sure of the best way to ensure the code is safe.

The addon manager could potentially open the plugin file for review and provide the option to enable the plugin or leave it disabled. However, I would rather implement a solution for this in the [new addon manager](https://github.com/LuaLS/lua-language-server/discussions/2408).

**Comment by fesily** [comment]
Okay, so wait for the new version.

**Comment by fesily** [comment]
Please give me a github copilot permission in luaCATS @carsakiller

**Comment by carsakiller** [comment]
@fesily it looks like copilot in organizations requires all the billing to be under the organization and isn't something that is just enabled. Maybe I am missing something though, I have never used copilot.

**Comment by fesily** [comment]
github is supposed to give free access to open source projects of a certain size, probably not yet

**Comment by carsakiller** [comment]
Huh, that is pretty cool. It looks like `LuaLS` doesn't even have access yet, unfortunately
